# Generated by Django 5.0.6 on 2024-05-13 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
    ]
