# Generated by Django 5.0.6 on 2024-05-14 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0003_recode_delete_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recode',
            old_name='adderss',
            new_name='address',
        ),
    ]
