# Generated by Django 5.0.6 on 2024-05-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0005_recode_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recode',
            old_name='Email',
            new_name='email',
        ),
        migrations.AddField(
            model_name='recode',
            name='phone',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
