# Generated by Django 5.0.6 on 2024-05-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0006_rename_email_recode_email_recode_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recode',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recode',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='recode',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='recode',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
    ]
